Increase PolyLine performance when indexing Vertices
mathnet/mathnet-spatial pull request #191
Opened 2021-08-19 16:59 UTC by G18SSY

Expose `IReadOnlyList<T>` instead of `IEnumerable<T>` for `PolyLine.Vertices`

This change allows external methods to index or operate on the vertices
without consuming additional memory by using `ToList()` or `ToArray()` or enumerating the entire collection
multiple times. This change still ensures that the internal list is immutable.

I don't think this is a breaking changes because `IReadOnlyList<T>` implements `IEnumerable<T>`, so anything that relies on `IEnumerable<T>` will still work.

This is implemented by using `ReadOnlyCollection<T>` internally instead of `List<T>`.

I think the same change would be appropriate for `Polygon2D` too but I'm not sure if there was a specific reason for using a custom implementation of `ImmutableList<T>` instead of `ReadOnlyCollection<T>`.

2023-03-07 06:37 UTC, cdrnet commented
Thank you!

Looks like I first need to upgrade the SDK to fix CI build before I can merge.

2023-03-24 16:17 UTC, jkalias requested changes
Please integrate master into this master. The CI bug has been fixed, so we can check if this PR passes

2023-03-24 16:17 UTC, jkalias commented on src/Spatial/Euclidean/PolyLine2D.cs
> +        private readonly ReadOnlyCollection<Point2D> points;
I am in a trajectory where I try to remove all redundant ```this.``` qualifiers from all classes. So please rename this private field to ```_points``` and remove all ```this.``` from these files.

2023-03-24 16:17 UTC, jkalias commented on src/Spatial/Euclidean/PolyLine3D.cs
> +        private readonly ReadOnlyCollection<Point3D> points;
Same comment as in ```PolyLine2D.cs```

2023-03-27 15:02 UTC, jkalias approved these changes

2023-03-27 15:10 UTC, merged